version: 2
jobs:

  test:
    docker:
      - image: rnestler/archlinux-rust:1.42.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - v1-cargo-cache-{{ arch }}
      - run:
          name: Build
          command: cargo build
      - run:
          name: Run tests
          command: cargo test
      - save_cache:
          key: v1-cargo-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - /root/.cargo

  lint:
    docker:
      - image: rnestler/archlinux-rust:1.42.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-lint-cache-{{ checksum "Cargo.lock" }}
            - v1-cargo-lint-cache-
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - save_cache:
          key: v1-cargo-lint-cache-{{ checksum "Cargo.lock" }}
          paths:
            - /root/.cargo

  fmt:
    docker:
      - image: rnestler/archlinux-rust:1.42.0
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  audit:
    docker:
      - image: rnestler/archlinux-rust:1.42.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cargo-audit-cache
      - run:
          name: Install cargo-audit
          command: cargo install --force cargo-audit
      - run:
          name: Run cargo-audit
          command: cargo audit
      - save_cache:
          key: v2-cargo-audit-cache
          paths:
            - /root/.cargo

workflows:
  version: 2

  # Build on push
  on_push:
    jobs:
      - test
      - lint
      - fmt
      - audit

  # Build master every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - lint
      - audit
