name: CI
on: [push]

env:
  RUSTUP_HOME: /root/.rustup

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    container: rnestler/archlinux-rust:1.63.0
    steps:
      - uses: actions/checkout@v3
      - run: cargo build
      - run: cargo test

  lint:
    runs-on: ubuntu-22.04
    container: rnestler/archlinux-rust:1.63.0
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    runs-on: ubuntu-22.04
    container: rnestler/archlinux-rust:1.63.0
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
